### ISSUE TITLE
Validation : Tester et améliorer le contraste des couleurs pour une meilleure lisibilité

### ISSUE THREAD

**Issue by abderrahmaneRabeh** [abderrahmaneRabeh/FUT_Champions_Web_App_Ultimate_Team#11]
Utiliser un outil comme WCAG Contrast Checker pour s'assurer que les contrastes respectent les normes d'accessibilité.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated the background color of the heading to meet WCAG contrast standards. Changed from red-400 to red-700 for better contrast with white text.

You can review changes in this commit: https://github.com/lkilu6456546/abderrahmaneRabeh-FUT_Champions_Web_App_Ultimate_Team-11/commit/b37d50ca14b08e90b354a363f46d9ffe7afc8814.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
